"use client"
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "./components/Header.js"
import {useEffect} from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}) {

    useEffect(() => {
        let lastScroll = window.ScrollY
        let header = document.getElementById("Header");
        let headerHeight = 100;

        function onScroll() {
            const currentScroll = window.scrollY;
            if (currentScroll > lastScroll) {
                header.style.transform = `translateY(-100%)`;
            } else {
                header.style.transform = `translateY(0)`;
            }
            lastScroll = currentScroll;
        }

        window.addEventListener("scroll", onScroll);
        return () => window.removeEventListener("scroll", onScroll);
    })

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Header/>
        {children}
        </body>
        </html>
    );
}
